version: "3.7"
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "ebcustom"
      POSTGRES_USER: "ebcustom"
      POSTGRES_DB: "ebcustom"
