- name: Create the nginx healthcheck log directory if it does not exist
  file:
    path: /var/log/nginx/healthd
    state: directory
    mode: '0755'

- name: Install nginx
  apt:
    name: nginx
    update_cache: yes

- name: Copy nginx.conf to /etc/nginx/nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'

- name: Copy ebcustom.conf to /etc/nginx/conf.d/ebcustom.conf
  copy:
    src: ebcustom.conf
    dest: /etc/nginx/conf.d/ebcustom.conf
    mode: '0644'
